
        #!/bin/sh

        ## name of Job
        #PBS -N snape_4_grenedalf

        ## Redirect output stream to this file.
        #PBS -o /media/inter/mkapun/projects/DESTv2/results/snape_4_log.txt

        ## Stream Standard Output AND Standard Error to outputfile (see above)
        #PBS -j oe

        ## Select a maximum of 100 cores and 800gb of RAM
        #PBS -l select=1:ncpus=100:mem=500gb

        ##### run analyses #####

        # activate the grenedalf environment
        module load Tools/grenedalf-0.1.0

        grenedalf diversity             --window-type regions             --window-region 4:1-1348131             --pool-sizes /media/inter/mkapun/projects/DESTv2/data/New_snape_pools_sub.txt             --sample-name-list /media/inter/mkapun/projects/DESTv2/data/New_snape_names_sub.txt             --measure all             --sync-path /media/inter/mkapun/projects/DESTv2/data/DEST2_snape_sub.sync.gz             --out-dir /media/inter/mkapun/projects/DESTv2/results/             --file-prefix snape_4             --window-region-skip-empty             --allow-file-overwriting             --threads 150             --min-coverage 2             --max-coverage 1000

        
