
    #!/bin/sh

    ## name of Job
    #PBS -N mapping

    ## Redirect output stream to this file.
    #PBS -o /media/inter/mkapun/projects/DESTv2/results/snape_filterSync_log.txt

    ## Stream Standard Output AND Standard Error to outputfile (see above)
    #PBS -j oe

    ## Select a maximum of 150 cores and 800gb of RAM
    #PBS -l select=1:ncpus=150:mem=800gb

    ##### run analyses #####

    gunzip -c /media/inter/mkapun/projects/DESTv2/data/DEST2_snape.sync.gz     | parallel     --jobs 150     --pipe     -k     --cat python3 /media/inter/mkapun/projects/DESTv2/scripts/filterSYNCbyName.py         --names /media/inter/mkapun/projects/DESTv2/data/names.txt         --pools /media/inter/mkapun/projects/DESTv2/data/pools.txt         --exclude /media/inter/mkapun/projects/DESTv2/data/exclude.txt         --input {}         --output /media/inter/mkapun/projects/DESTv2/data/New         > /media/inter/mkapun/projects/DESTv2/data/DEST2_snape_sub.sync.gz

    
