---
title: "Statistical Analysis Of Inversion Marker Frequencies"
author: "S.Steindl"
date: '2023-07-24'
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#                                 TYPE 3 ANOVA 

```{r libraries, include=FALSE}
library(car)
library(readr)
library(knitr)
library(ggplot2)
library(dplyr)
```

```{r prepare_data, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
meta <- read.csv("/media/DEST2_NHM/data/dest_v2.samps_25Feb2023.csv", row.names=1)

#POOL-SNP
nhm_inversion <- read.delim("/media/DEST2_NHM/results/PoolSNP_nhm_inversion.af", row.names=1)
for (col in colnames(nhm_inversion)){
  nhm_inversion[[col]] <- as.numeric(paste(nhm_inversion[[col]]))
}  

joined_table <- merge(meta[3:5], nhm_inversion, by = "row.names")
rownames(joined_table) <- rownames(meta)
data <- merge(meta[13:14], joined_table, by ="row.names")

##Get Coverages for correspronding data set
mean_coverages <- read.csv("/media/DEST2_NHM/output/CoveragesPoolSNP.csv", header=FALSE)
cov <- t(round(mean_coverages))
data$cov <- cov[,1] 
data <- na.omit(data) 

#Inversions
inversions=c("In.3R.Payne", "In.2L.t", "In.2R.Ns", "In.3R.C", "In.3R.K", "In.3R.Mo", "In.3L.P")

for (i in 8:14){
  #print(data[i])
  x <- paste("ANOV_",colnames(data[i]),"_1", sep="")
  x2 <- paste("ANOV_",colnames(data[i]),"_2", sep="")
  v <- round(data[i]*data$cov)
  v2 <- round(data$cov - round(data[i]*data$cov,0),0)
  p <- assign(x,v)
  p2 <- assign(x2,v2)
  colnames(p) <- x
  colnames(p2) <- x2
  data <- cbind(data,p)
  data <- cbind(data,p2)
}

my_splits <- split(data, data$continent)
split_names <- c("Africa",           
                 "Asia",
                 "Europe",
                 "North_America","Oceania", "South_America")
for (i in 1:length(my_splits)) {       
  assign(split_names[i], my_splits[[i]])
}
ContList <- list(Africa, Asia, Europe, North_America, Oceania, South_America)

#ANOVA Type3 


#function for 3 paramters inclduing continent, usable globally 
latloncont <- function(subs){
  data=subs
  for (inv in inversions){
    t <- paste(inv,"_test", sep="")
    c1 <- paste("ANOV_",inv,"_1", sep="")
    c2 <- paste("ANOV_",inv,"_2", sep="")
    #print(data[[c1]] )
    x <- glm(cbind(data[[c1]] ,data[[c2]])~lat*long*continent,data=data,family="binomial" )
    r <- car::Anova(x, type=3)
    print(kable(r, format="pandoc", caption = paste(inv)))
    #cat("\n")
    #assign(t,x)
  } 
}



###

latlon <- function(subs){
  data <- subs
  for (inv in inversions){
    t <- paste(inv,"_test", sep="")
    c1 <- paste("ANOV_",inv,"_1", sep="")
    c2 <- paste("ANOV_",inv,"_2", sep="")
    #print(data[[c1]] )
    x <- glm(cbind(data[[c1]] ,data[[c2]])~lat*long,data=data,family="binomial" )
    r <- car::Anova(x, type=3)
    #kable(r, format="pandoc", caption = paste(inv))
    print(kable(r, format="pandoc", caption = paste(inv)))
    #cat("\n")
    #assign(t,x)
  } 
}  

#lapply(ContList, latlon(x))

```
# All Inversions - Global

```{r plot, echo= FALSE,comment="", prompt=TRUE, fig.align="center"} 

latloncont(data)

```

# All Inversions Per Continent

## 1) Europe
```{r plotEurope, echo= FALSE,  comment="", prompt=TRUE} 
latlon(Europe)

```

## 2) North America
```{r plotNA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(North_America)
```

## 3) South America
```{r plotSA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(South_America)
```
## 4) Oceania
```{r plotOA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(Oceania)
```
## 5) Africa
```{r plotA, echo= FALSE,  comment="", prompt=TRUE} 
latlon(Africa)
```



# Average Frequencies and Standard Deviation 

```{r calculateBasics, include= FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
PoolSNP_nhm_inversion <- read_table2("/media/ssteindl/DESTv2_data_paper/misc/Inversions/results/PoolSNP_nhm_inversion.af",
col_types = cols(`In(2L)t` = col_number(),
`In(2R)Ns` = col_number(), `In(3L)P` = col_number(),
`In(3R)C` = col_number(), `In(3R)K` = col_number(),
`In(3R)Mo` = col_number(), `In(3R)Payne` = col_number()))
View(PoolSNP_nhm_inversion)

inversions <- na.omit(PoolSNP_nhm_inversion[2:8])
means <- colMeans(inversions, na.rm = T)
SDs <- apply(inversions,2,sd)
assign("SDs", SDs, envir = .GlobalEnv) 
```

# Averages
```{r summries, echo=FALSE} 
summary(inversions)

```

# Standard Deviations

```{r SDs, echo=FALSE} 
SDs
```

# Regression Slope across Years
```{r regressionSlopes, include=FALSE} 
meta <- read.csv("/media/DEST2_NHM/data/dest_v2.samps_25Feb2023.csv", row.names=1)
nhm_inversion <- read.delim("/media/DEST2_NHM/results/PoolSNP_nhm_inversion.af", row.names=1)
for (col in colnames(nhm_inversion)){
  nhm_inversion[[col]] <- as.numeric(paste(nhm_inversion[[col]]))
}  

joined_table <- merge(meta[3:5], nhm_inversion, by = "row.names")
rownames(joined_table) <- rownames(meta)
data <- merge(meta[13:14], joined_table, by ="row.names")
data2 <- na.omit(data) 

NAm <- subset(data2, continent=="North_America" )
Europe <- subset(data2, continent=="Europe" )

fit_glm_for_group <- function(data, year) {
  if (nrow(data) > 10) {  # Filter to have at least 10 samples for each year
    glm_model <- glm(In.2L.t ~ lat, data = data, family = binomial)
    # For linear regression, use: lm(In3Payner ~ lat, data = data)
    return(data.frame(year = year, coef_glm = coef(glm_model)["lat"]))
  } else {
    return(NULL)  # Return NULL for years with less than 10 samples (insufficient data)
  }
}

glm_results_Europe <- Europe %>%
  group_by(year) %>%
  filter(n() > 10) %>%
  do(fit_glm_for_group(., year = first(.$year))) %>%
  ungroup()
anova_result <- aov(coef_glm ~ year, data = glm_results_Europe)


```

```{r regressionSlopesResults} 
print(glm_results_Europe)
print(summary(anova_result))
```



